// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvdlrzvtozyhmiodftov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12ZGxyenZ0b3p5aG1pb2RmdG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzM1NDksImV4cCI6MjA1NzkwOTU0OX0.7kkcunBJl6aa_SpTtlioDBSdMvxwGCHfan218lPS8-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);